// templates/react-ts-tailwind/src/RatingApp.tsx
import { useState } from 'react';

import OverallSatisfaction from './OverallSatisfaction';
import { Product } from './ProductModel';
import ProductSatisfaction from './ProductSatisfaction';

interface RatingAppProps {
  products: Product[];
}

const RatingApp = (props: RatingAppProps) => {
  const totalRating = (total: number, product: Product) => total + product.rating;
  const averageRating = (products: Product[]) => Math.floor(products.reduce(totalRating, 0) / products.length);

  const [products, setProducts] = useState(props.products);
  const [overallRating, setOverallRating] = useState(averageRating(props.products));

  const handleProductRatingChange = (e: { productId: string; rating: number }) => {
    const newProducts = [...products];
    const index = newProducts.findIndex((p) => p.id === e.productId);
    newProducts[index].rating = e.rating;

    setProducts(newProducts);
    setOverallRating(averageRating(newProducts));
  };

  return (
    <>
      <h1 className="mt-12 text-center text-4xl font-semibold text-indigo-900 lg:text-5xl">
        {products.map((p) => p.title).join(' - ')}
      </h1>
      <div id="products" className="m-4 grid grid-flow-row gap-4 lg:mt-8 lg:grid-flow-col">
        {products.map((p) => (
          <ProductSatisfaction product={p} key={p.id} productRatingChange={handleProductRatingChange} />
        ))}
        <OverallSatisfaction rating={overallRating} />
      </div>
    </>
  );
};

export default RatingApp;

// examples/lit-ts-tailwind-cypress-storybook/src/rating-app.ts
import './product-satisfaction';
import './overall-satisfaction';

import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';

import { allProducts, Product } from './product.model';
import { TwLitElement } from './tailwind';

@customElement('rating-app')
export class RatingApp extends TwLitElement {
  @state() private overallRating = 0;

  @property({ type: Array }) products = allProducts;

  willUpdate(changedProperties: Map<string, object>) {
    if (changedProperties.has('products')) {
      this.overallRating = this.getAverageRating();
    }
  }

  render() {
    return html`
      <h1 class="my-4 text-center text-3xl font-semibold text-indigo-900 lg:my-12 lg:text-5xl">
        ${this.products.map((p) => p.title).join(' - ')}
      </h1>
      <main
        data-testid="products"
        class="mx-auto mt-4 grid max-w-6xl grid-flow-row gap-4 p-4 lg:grid-flow-col lg:grid-cols-3"
      >
        ${this.products.map(
          (p) =>
            html`<product-satisfaction
              .product="${p}"
              @product-rating-change="${this.handleProductRatingChange}"
            ></product-satisfaction>`
        )}
        <overall-satisfaction overall-rating="${this.overallRating}"></overall-satisfaction>
      </main>
    `;
  }

  private handleProductRatingChange(e: CustomEvent) {
    const { productId, rating } = e.detail;
    const index = this.products.findIndex((p) => p.id === productId);
    this.products[index].rating = rating;
    this.overallRating = this.getAverageRating();
  }

  private getAverageRating() {
    return Math.floor(this.products.reduce(this.totalRating, 0) / this.products.length);
  }

  private totalRating(total: number, product: Product) {
    return total + product.rating;
  }
}
