// templates/lit-ts/src/product-satisfaction.ts
import { LitElement, css, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';

import { Product } from './product.model';
import './rating-container';

@customElement('product-satisfaction')
export class ProductSatisfaction extends LitElement {
  static styles = css`
    .product-satisfaction {
      display: flex;
      flex-direction: column;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      border-radius: 0.5rem;
      padding: 1rem;
      text-align: center;
    }

    .product-satisfaction a {
      display: block;
      color: var(--indigo900);
      font-weight: 500;
      font-size: 1.5rem;
      text-decoration: none;
      margin-bottom: 1rem;
    }

    .product-satisfaction span {
      flex: 1 1 auto;
    }

    @media screen and (min-width: 1024px) {
      .product-satisfaction {
        padding: 2rem;
      }

      .product-satisfaction a {
        font-size: 1.8rem;
      }

      .product-satisfaction span {
        height: 1.5rem;
      }
    }
  `;

  @property({ type: Object }) product: Product = null as unknown as Product;

  render() {
    return html`
      <div data-testid="${this.product.id}" class="product-satisfaction">
        <a href="${this.product.url}">${this.product.title}</a>
        <span>${this.product.description}</span>
        <rating-container product-id="${this.product.id}" rating="${this.product.rating}" clickable></rating-container>
      </div>
    `;
  }
}

// examples/vue-ts-playwright-histoire/src/ProductSatisfaction.vue
<script setup lang="ts">
import { Product } from './ProductModel';
import { ProductRatingEventArgs } from './RatingAppModel';
import RatingContainer from './RatingContainer.vue';

const props = defineProps<{
  product: Product;
}>();

const emit = defineEmits<(e: 'productRatingChange', args: ProductRatingEventArgs) => void>();

const handleRatingContainerChange = (eventArgs: ProductRatingEventArgs) => {
  emit('productRatingChange', eventArgs);
};
</script>

<template>
  <section class="product-satisfaction">
    <a :href="props.product.url">{{ props.product.title }}</a>
    <span>{{ props.product.description }}</span>
    <RatingContainer
      :product-id="props.product.id"
      :rating="props.product.rating"
      clickable
      @product-rating-change="handleRatingContainerChange"
    />
  </section>
</template>

<style scoped="true">
.product-satisfaction {
  display: flex;
  flex-direction: column;
  box-shadow:
    0 4px 8px 0 rgba(0, 0, 0, 0.2),
    0 6px 20px 0 rgba(0, 0, 0, 0.19);
  border-radius: 0.5rem;
  padding: 1rem;
  text-align: center;
}

.product-satisfaction a {
  display: block;
  color: var(--indigo900);
  font-weight: 500;
  font-size: 1.5rem;
  text-decoration: none;
  margin-bottom: 1rem;
}

.product-satisfaction span {
  flex: 1 1 auto;
}

@media screen and (min-width: 1024px) {
  .product-satisfaction {
    padding: 2rem;
  }

  .product-satisfaction a {
    font-size: 1.8rem;
  }

  .product-satisfaction span {
    height: 2.5rem;
  }
}
</style>
