// templates/react-ts/src/ProductSatisfaction.tsx
import './ProductSatisfaction.css';

import { Product } from './ProductModel';
import RatingContainer from './RatingContainer';

export interface ProductSatisfactionProps {
  product: Product;
  productRatingChange: (event: { productId: string; rating: number }) => void;
}

const ProductSatisfaction = (props: ProductSatisfactionProps) => {
  return (
    <section data-testid={props.product.id} className="product-satisfaction">
      <a href={props.product.url}>{props.product.title}</a>
      <span>{props.product.description}</span>
      <RatingContainer
        productId={props.product.id}
        rating={props.product.rating}
        clickable={true}
        productRatingChange={props.productRatingChange}
      />
    </section>
  );
};

export default ProductSatisfaction;

// examples/svelte-ts-cypress-storybook/src/ProductSatisfaction.svelte
<script lang="ts">
  import './ProductSatisfaction.css';

  import type { Product } from './ProductModel';
  import RatingContainer from './RatingContainer.svelte';

  export let product: Product;
</script>

<section data-testid="{product.id}" class="product-satisfaction">
  <a href="{product.url}">{product.title}</a>
  <span>{product.description}</span>
  <RatingContainer productId="{product.id}" rating="{product.rating}" clickable="{true}" on:productRatingChange />
</section>
