// examples/vue-ts-tailwind-cypress-storybook/src/SatisfactionStar.vue
<script setup lang="ts">
import { ProductRatingEventArgs } from './RatingAppModel';

const props = defineProps<{
  productId: string;
  position: number;
  checked: boolean;
  clickable: boolean;
}>();

const emit = defineEmits<(event: 'starClick', args: ProductRatingEventArgs) => void>();

const handleStarClick = () => {
  if (props.clickable) {
    emit('starClick', { productId: props.productId, rating: props.position });
  }
};
</script>

<template>
  <font-awesome-icon
    :data-testid="`${props.productId}-${props.position}`"
    :class="[
      props.checked ? 'text-orange-500' : '',
      props.clickable ? 'cursor-pointer hover:text-orange-700' : !props.checked ? 'text-white' : ''
    ]"
    icon="fa-solid fa-star"
    size="2x"
    role="presentation"
    @click="handleStarClick"
  />
</template>

// templates/react-ts-tailwind/src/SatisfactionStar.tsx
import { useEffect, useState } from 'react';

export interface SatisfactionStarProps {
  productId: string;
  position: number;
  checked: boolean;
  clickable: boolean;
  starClick: (event: { productId: string; rating: number }) => void;
}

const SatisfactionStar = (props: SatisfactionStarProps) => {
  const [className, setClassName] = useState('');

  useEffect(() => {
    let classes = 'fa fa-star mx-1 text-3xl';
    if (props.checked) {
      classes += ' text-orange-500';
    }
    if (props.clickable) {
      classes += ' cursor-pointer hover:text-orange-700';
    } else if (!props.checked) {
      classes += ' text-white';
    }

    setClassName(classes);
  }, [props.checked, props.clickable]);

  return (
    <span
      id={`${props.productId}-${props.position}`}
      className={className}
      role="presentation"
      onClick={() => props.starClick({ productId: props.productId, rating: props.position })}
    ></span>
  );
};

export default SatisfactionStar;
