// examples/vue-ts-cypress-storybook/src/SatisfactionStar.vue
<script setup lang="ts">
import { ProductRatingEventArgs } from './RatingAppModel';

const props = defineProps<{
  productId: string;
  position: number;
  checked: boolean;
  clickable: boolean;
}>();

const emit = defineEmits<(event: 'starClick', args: ProductRatingEventArgs) => void>();

const handleStarClick = () => {
  if (props.clickable) {
    emit('starClick', { productId: props.productId, rating: props.position });
  }
};
</script>

<template>
  <font-awesome-icon
    :data-testid="`${props.productId}-${props.position}`"
    :class="{ checked: props.checked, action: props.clickable }"
    icon="fa-solid fa-star"
    size="2x"
    @click="handleStarClick"
  />
</template>

<style scoped="true">
.checked {
  color: var(--orange500);
}

.action {
  cursor: pointer;
}

.action:hover {
  color: var(--orange700);
}
</style>

// examples/svelte-ts-tailwind-cypress-storybook/src/SatisfactionStar.svelte
<script lang="ts">
  import { faStar } from '@fortawesome/free-solid-svg-icons/faStar';
  import Icon from 'fa-svelte';
  import { createEventDispatcher } from 'svelte';

  import type { ProductRatingEventArgs } from './RatingAppModel';

  const icon = faStar;
  const dispatch = createEventDispatcher<{ starClick: ProductRatingEventArgs }>();

  const handleStarClick = () => {
    if (clickable) {
      dispatch('starClick', { productId, rating: position });
    }
  };

  export let productId: string;
  export let position: number;
  export let checked: boolean;
  export let clickable: boolean;

  $: dataTestId = `${productId}-${position}`;
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div
  class="outline-none"
  data-testid="{dataTestId}"
  aria-label="{dataTestId}"
  role="button"
  tabindex="0"
  on:click="{handleStarClick}"
>
  <Icon
    {icon}
    class="text-3xl {checked ? 'text-orange-500' : ''} {clickable
      ? 'cursor-pointer hover:text-orange-700'
      : !checked
        ? 'text-white'
        : ''}"
  />
</div>
